<?php

/**
 * @file
 * Contains the n2t.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function n2t_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  if ($form_id == 'persistent_identifiers_admin_settings') {
    $config = \Drupal::config('n2t.settings');
    $form['n2t_user'] = [
      '#type' => 'textfield',
      '#access' => TRUE,
      '#title' => 'N2T username',
      '#default_value' => $config->get('n2t_user'),
      '#states' => [
        'visible' => [
          ':input[id="persistent_identifiers_minter"]' => ['value' => 'n2t.minter.n2t'],
        ],
      ],
    ];

    $form['n2t_password'] = [
      '#type' => 'textfield',
      '#title' => 'N2T password',
      '#default_value' => $config->get('n2t_password'),
      '#description' => t("The password used to authenticate for the N2T API."),
      '#states' => [
        'visible' => [
          ':input[id="persistent_identifiers_minter"]' => ['value' => 'n2t.minter.n2t'],
        ],
      ],
    ];

    $form['n2t_api_endpoint'] = [
      '#type' => 'textfield',
      '#access' => TRUE,
      '#title' => 'N2T API endpoint',
      '#default_value' => $config->get('n2t_api_endpoint'),
      '#description' => t("Full URL to the N2T API endpoint."),
      '#states' => [
        'visible' => [
          ':input[id="persistent_identifiers_minter"]' => ['value' => 'n2t.minter.n2t'],
        ],
      ],
    ];

    $form['n2t_shoulder'] = [
      '#type' => 'textfield',
      '#access' => TRUE,
      '#title' => 'Namespace and shoulder',
      '#default_value' => $config->get('n2t_shoulder'),
      '#description' => t("The NAAN namespace and shoulder (joined by a /) used for minting ARKs. E.g. '99999/fq3'. You must get this from N2T."),
      '#states' => [
        'visible' => [
          ':input[id="persistent_identifiers_minter"]' => ['value' => 'n2t.minter.n2t'],
        ],
      ],
    ];

    $form['n2t_local_branding_resolver'] = [
      '#type' => 'textfield',
      '#access' => TRUE,
      '#title' => 'Branded ARK resolver base URL',
      '#default_value' => $config->get('n2t_local_branding_resolver'),
      '#description' => t('The pattern to replace the N2T host with when publishing ARKs, e.g. "https://ids.mydomain.edu/". This requires set up of a "branded" resolver as described in the N2T API documentation. Leave blank if you are not using branded ARKs.'),
      '#states' => [
        'visible' => [
          ':input[id="persistent_identifiers_minter"]' => ['value' => 'n2t.minter.n2t'],
        ],
      ],
    ];

    $form['n2t_identifier_metadata'] = [
      '#weight' => 80,
      '#type' => 'checkbox',
      '#default_value' => $config->get('n2t_identifier_metadata'),
      '#description' => t("Add the persistent identifier's required 'who', 'what', 'when', 'how' metadata to the ARK record as documented in the N2T API docs. Currently only 'what' is populated, with the node's title. Other elements are given placeholder values."),
      '#title' => t('Add basic identifier metadata'),
      '#states' => [
        'visible' => [
          ':input[id="persistent_identifiers_minter"]' => ['value' => 'n2t.minter.n2t'],
        ],
      ],
    ];


    $form['#submit'][] = 'n2t_submit';
  }
}

/**
 * Submit callback.
 *
 * Saves the value of the minter-specific field defined in the implementation
 * of hook_form_alter() above.
 *
 * @param array $form
 *   The form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state.
 */
function n2t_submit(array &$form, FormStateInterface $form_state) {
  $existing_config = \Drupal::config('n2t.settings');
  $n2t_user = $form_state->getValue('n2t_user', $existing_config->get('n2t_user'));
  $n2t_password = $form_state->getValue('n2t_password', $existing_config->get('n2t_password'));

  $n2t_api_endpoint = $form_state->getValue('n2t_api_endpoint', $existing_config->get('n2t_api_endpoint'));
  $n2t_shoulder = $form_state->getValue('n2t_shoulder', $existing_config->get('n2t_shoulder'));
  $n2t_local_branding_resolver = $form_state->getValue('n2t_local_branding_resolver', $existing_config->get('n2t_local_branding_resolver'));
  $n2t_identifier_metadata = $form_state->getValue('n2t_identifier_metadata', $existing_config->get('n2t_identifier_metadata'));

  // Save password in Drupal state.
  $state = \Drupal::state();
  if (!empty($form_state->getValue('n2t_password'))) {
    $state->set('n2t.password', $form_state->getValue('n2t_password'));
  }

  $config_factory = \Drupal::configFactory();
  $config_factory->getEditable('n2t.settings')
    ->set('n2t_user', trim($n2t_user))
    ->set('n2t_password', trim($n2t_password))
    ->set('n2t_api_endpoint', trim($n2t_api_endpoint))
    ->set('n2t_shoulder', trim($n2t_shoulder))
    ->set('n2t_local_branding_resolver', trim($n2t_local_branding_resolver))
    ->set('n2t_identifier_metadata', trim($n2t_identifier_metadata))
    ->save();
}
